version: "3"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    container_name: postgres-container
    volumes:
      - ./server/db/postgres:/var/lib/postgres
      - ./server/db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
    hostname: postgres
    user: root
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8000:80"
    volumes:
      - ./db/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: desert_shift@yahoo.co.jp     # pgAdmin Address
      PGADMIN_DEFAULT_PASSWORD: root  # pgAdmin Password
    hostname: pgadmin4
    links:
      - postgres
    restart: always
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    container_name: api-container
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=shift-db
      - POSTGRES_PASSWORD=qNcy&uLf!2n^4##a
      - POSTGRES_PORT=5432
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - node_modules_volume:/app/node_modules
      - ./client:/app
volumes:
    node_modules_volume: